In [6]:
import numpy as np

In [3]:
# Creating Numpy Arrays

In [4]:
my_list = [1,2,3]

In [6]:
my_np_list = np.array(my_list)

In [7]:
type(my_np_list)

numpy.ndarray

In [8]:
type(my_list)

list

In [9]:
my_matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [11]:
my_np_matrix = np.array(my_matrix)

In [12]:
type(my_matrix)

list

In [13]:
type(my_np_matrix)

numpy.ndarray

In [14]:
my_np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
list(range(0,4))

[0, 1, 2, 3]

In [16]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros(3, int)

array([0, 0, 0])

In [22]:
np.zeros((5,4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
np.ones((5,6), int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [8]:
np.linspace(0, 10, 1)

array([0.])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
arr = np.arange(25)

In [21]:
narra = np.random.randint(0, 50, 10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
narra

array([16,  6, 49, 31, 44,  8, 10, 10, 21, 29])

In [26]:
arr.reshape(2, 13)

ValueError: cannot reshape array of size 25 into shape (2,13)

In [28]:
narra.reshape(5,2)

array([[16,  6],
       [49, 31],
       [44,  8],
       [10, 10],
       [21, 29]])

In [30]:
arr.shape

(25,)

In [31]:
narra.shape

(10,)

In [35]:
narra.max()

49

In [36]:
arr+arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [38]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])